group: edge
language: java
jdk: oraclejdk8
install: true
before_install:
  - gradle -v
  - rm -rf $HOME/.gradle
script:
  - gradle testrunner loadtestrunner --stacktrace
  - bash gradlew testrunner loadtestrunner --stacktrace
before_cache:
  - gradle --stop
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/gradle.plugin*
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
