group: edge
language: java
jdk: oraclejdk8
install: true
script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/daggerok/soapui-runner
  - cd soapui-runner
  - git branch -a
  - git checkout v5.2.1
  - bash gradlew clean assemble publish
  - cd $TRAVIS_BUILD_DIR
  - bash gradlew testrunner loadtestrunner --stacktrace
before_cache:
  - gradle --stop
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
