group: edge
language: java
jdk: oraclejdk8
install: true
script:
  - >
    for version in 2.8 2.9 2.10 2.11 2.12 2.13 2.14 3.0 3.1 3.2 3.3 3.4 3.4.1 3.5 4.0 4.0.1 4.0.2; do
      gradle wrapper --gradle-version $version;
      bash gradlew -v;
      bash gradlew extDir testrunner loadtestrunner --stacktrace;
      rm -rf $HOME/.gradle;
    done;
before_cache:
  - gradle --stop
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
